# Generated by Django 4.0.4 on 2022-04-28 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuestroUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='curso',
        ),
        migrations.DeleteModel(
            name='entregable',
        ),
        migrations.DeleteModel(
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='profesor',
        ),
    ]
