# Generated by Django 4.0.4 on 2022-05-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
